#!/usr/bin/env python3
"""Workspace management CLI.

Usage:
    python scripts/tools/workspace.py create <slug>
    python scripts/tools/workspace.py list
    python scripts/tools/workspace.py archive <slug>
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))

try:
    import yaml
except ImportError:
    print("Error: pyyaml not installed. Run: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

from workspace_config import internal_dir as _internal_dir, is_within_workspace

import harness_config as _hc


def _workspaces_base() -> Path:
    return (ROOT / _hc.workspaces_dir()).resolve()


def _slug_valid(slug: str) -> bool:
    return bool(re.match(r"^[a-z0-9][a-z0-9-]*$", slug))


def _load_cfg(ws_dir: Path) -> dict:
    ws_yaml = ws_dir / "workspace.yaml"
    if not ws_yaml.exists():
        return {}
    return yaml.safe_load(ws_yaml.read_text(encoding="utf-8")) or {}


def _scaffold(ws_dir: Path, docs_dir: Path | None = None) -> None:
    """Create directory structure. docs_dir defaults to ws_dir/internal."""
    if docs_dir is None:
        docs_dir = ws_dir / "internal"
    for sub in ["tickets/open", "tickets/closed", "archive"]:
        (docs_dir / sub).mkdir(parents=True, exist_ok=True)
    for sub in ["client/tickets/open", "client/tickets/closed"]:
        (ws_dir / sub).mkdir(parents=True, exist_ok=True)
    template_src = ROOT / "docs" / "tickets" / "TEMPLATE.md"
    if template_src.exists():
        shutil.copy(template_src, docs_dir / "tickets" / "TEMPLATE.md")


def _write_initial_files(ws_dir: Path, docs_dir: Path, name: str) -> None:
    (docs_dir / "sessions.md").write_text(
        f"# Session Log — {name}\n\n"
        "## Current Phase & Status\n\n*(Rewritten each session)*\n\n_No sessions yet._\n\n---\n\n"
        "## Active Work\n\n**S000 — no sessions yet**\n\n---\n\n"
        "## Session Log\n\n",
        encoding="utf-8",
    )
    (docs_dir / "opus_notes.md").write_text(
        f"# Opus Notes — {name}\n\n_No reviews yet._\n",
        encoding="utf-8",
    )
    (docs_dir / "tickets" / "INDEX.md").write_text(
        "# Ticket Index\n\n"
        "_Generated by generate_ticket_index.py — do not edit by hand._\n\n"
        "0 open tickets.\n",
        encoding="utf-8",
    )
    (ws_dir / "client" / "progress.md").write_text(
        f"# Progress — {name}\n\n_No sessions completed yet._\n",
        encoding="utf-8",
    )
    (ws_dir / "CLAUDE.md").write_text(
        f"# {name}\n\n"
        "This workspace is managed by the Claude harness.\n\n"
        "## Session protocol\n\n"
        "At session start, run `/session-start`. Context files for this workspace:\n\n"
        "- `sessions.md` — session log\n"
        "- `tickets/INDEX.md` — ticket overview\n"
        "- `opus_notes.md` — Opus review history\n\n"
        "## Repos\n\n"
        "_See workspace.yaml for declared repos._\n",
        encoding="utf-8",
    )


def cmd_create(args: argparse.Namespace) -> None:
    slug = args.slug
    if not _slug_valid(slug):
        print(
            f"Error: slug '{slug}' is invalid. Use lowercase letters, digits, and hyphens.",
            file=sys.stderr,
        )
        sys.exit(1)

    ws_base = _workspaces_base()
    ws_dir = ws_base / slug

    if ws_dir.exists():
        print(f"Error: workspace '{slug}' already exists at {ws_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Creating workspace: {slug}")
    name = input("Name (human-readable): ").strip() or slug
    ws_type = ""
    while ws_type not in ("client", "personal"):
        ws_type = input("Type [client/personal]: ").strip().lower()
        if ws_type not in ("client", "personal"):
            print("  Enter 'client' or 'personal'.")

    repos: list[dict] = []
    print("Repos (blank name to finish):")
    while True:
        repo_name = input("  Repo name (e.g. 'backend'): ").strip()
        if not repo_name:
            if not repos:
                print("  At least one repo is required.")
                continue
            break
        repo_path_str = input(f"  Path for '{repo_name}': ").strip()
        if not repo_path_str:
            continue
        repo_path = Path(repo_path_str).expanduser().resolve()
        if not repo_path.exists():
            print(f"  WARNING: path does not exist on disk: {repo_path}")
        role = "primary" if not repos else (
            input("  Role [primary/secondary] (default: secondary): ").strip() or "secondary"
        )
        repos.append({"name": repo_name, "path": str(repo_path), "role": role})

    client_remote = ""
    if ws_type == "client":
        client_remote = input("Client git remote URL (leave blank to configure later): ").strip()

    docs_path_str = input(
        "Docs path inside primary repo (blank = harness-local default, e.g. ~/projects/myapp/.harness): "
    ).strip()
    docs_path_resolved: Path | None = None
    if docs_path_str:
        docs_path_resolved = Path(docs_path_str).expanduser().resolve()
        temp_ws = {"repos": repos}
        if not is_within_workspace(docs_path_resolved, temp_ws):
            print(
                f"Error: docs_path '{docs_path_resolved}' must be inside one of the declared repos.",
                file=sys.stderr,
            )
            sys.exit(1)

    ws_dir.mkdir(parents=True)
    docs_dir = docs_path_resolved if docs_path_resolved else ws_dir / "internal"
    _scaffold(ws_dir, docs_dir)
    _write_initial_files(ws_dir, docs_dir, name)

    cfg: dict = {
        "name": name,
        "type": ws_type,
        "status": "active",
        "opened": date.today().isoformat(),
        "repos": repos,
    }
    if docs_path_resolved:
        cfg["docs_path"] = str(docs_path_resolved)
    if client_remote:
        cfg["client_remote"] = client_remote

    (ws_dir / "workspace.yaml").write_text(
        yaml.dump(cfg, default_flow_style=False, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )

    print(f"\nWorkspace created: workspaces/{slug}/")
    print(f"  Sessions:    {docs_dir}/sessions.md")
    print(f"  Tickets:     {docs_dir}/tickets/")
    print(f"  Repos ({len(repos)}):")
    for r in repos:
        print(f"    [{r['role']:>9}] {r['name']}: {r['path']}")
    if client_remote:
        print(f"  Client remote: {client_remote}")
    print(f"\nOpen Claude Code at workspaces/{slug}/ to start a session.")


def cmd_list(args: argparse.Namespace) -> None:
    ws_base = _workspaces_base()
    if not ws_base.exists():
        print("No workspaces directory.")
        return

    workspaces = []
    for ws_dir in sorted(ws_base.iterdir()):
        if not ws_dir.is_dir() or ws_dir.name == "archive":
            continue
        cfg = _load_cfg(ws_dir)
        if not cfg or cfg.get("status") == "archived":
            continue

        docs = _internal_dir(ws_dir, cfg)
        tickets_dir = docs / "tickets" / "open"
        ticket_count = len(list(tickets_dir.glob("T*.md"))) if tickets_dir.exists() else 0

        last_session = "—"
        sessions_path = docs / "sessions.md"
        if sessions_path.exists():
            import re as _re
            matches = _re.findall(r"S\d+ (\d{4}-\d{2}-\d{2}):", sessions_path.read_text())
            if matches:
                last_session = matches[-1]

        raw_repos = cfg.get("repos", [])
        workspaces.append(
            dict(
                slug=ws_dir.name,
                name=cfg.get("name", ws_dir.name),
                ws_type=cfg.get("type", "?"),
                repos=len(raw_repos),
                repo_list=raw_repos,
                tickets=ticket_count,
                last=last_session,
            )
        )

    if not workspaces:
        print("No active workspaces.")
        return

    print(f"{'Slug':<25} {'Name':<35} {'Type':<10} {'Repos':>5} {'Tickets':>7}  Last session")
    print("-" * 98)
    for w in workspaces:
        print(
            f"{w['slug']:<25} {w['name']:<35} {w['ws_type']:<10}"
            f" {w['repos']:>5} {w['tickets']:>7}  {w['last']}"
        )
        for r in w["repo_list"]:
            role = r.get("role", "secondary")
            repo_name = r.get("name", "?")
            repo_path = str(Path(r.get("path", "")).expanduser()).replace(
                str(Path.home()), "~", 1
            )
            print(f"  [{role:>9}] {repo_name}: {repo_path}")


def cmd_archive(args: argparse.Namespace) -> None:
    slug = args.slug
    ws_base = _workspaces_base()
    ws_dir = ws_base / slug

    if not ws_dir.exists():
        print(f"Error: workspace '{slug}' not found.", file=sys.stderr)
        sys.exit(1)

    archive_base = ws_base / "archive"
    archive_base.mkdir(exist_ok=True)
    dest = archive_base / slug

    if dest.exists():
        print(f"Error: archive destination already exists: {dest}", file=sys.stderr)
        sys.exit(1)

    ws_yaml = ws_dir / "workspace.yaml"
    if ws_yaml.exists():
        cfg = yaml.safe_load(ws_yaml.read_text(encoding="utf-8")) or {}
        cfg["status"] = "archived"
        ws_yaml.write_text(
            yaml.dump(cfg, default_flow_style=False, allow_unicode=True, sort_keys=False),
            encoding="utf-8",
        )

    shutil.move(str(ws_dir), str(dest))
    print(f"Archived: workspaces/{slug}/ → workspaces/archive/{slug}/")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Claude harness workspace management",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command", metavar="<command>")

    p_create = sub.add_parser("create", help="Create a new workspace")
    p_create.add_argument("slug", help="Workspace slug (lowercase, hyphens ok)")

    sub.add_parser("list", help="List active workspaces")

    p_archive = sub.add_parser("archive", help="Archive a workspace")
    p_archive.add_argument("slug", help="Workspace slug to archive")

    args = parser.parse_args()

    if args.command == "create":
        cmd_create(args)
    elif args.command == "list":
        cmd_list(args)
    elif args.command == "archive":
        cmd_archive(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
